name: Flask API CI with Docker

on:
  push:
    branches:
      - main
  #pull_request:
   # branches:
  #    - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python (optional, for dependencies check)
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run Unit Tests
    #- name: Run tests
     # run: pytest

    # Step 5: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t flask-api:latest .

    # Step 6: Run Docker Container
    - name: Run Docker Container
      run: |
        docker run -d -p 5000:5000 --name flask-api-test flask-api:latest

    # Step 7: Test Flask API
    - name: Test Flask API
      run: |
        sleep 5  # Give time for the container to start
        curl http://localhost:5000/get-items || exit 1

    # Step 8: Stop and Remove Docker Container
   # - name: Clean up Docker
    #  run: |
   #     docker stop flask-api-test
  #      docker rm flask-api-test
